# Generated by Django 3.2.7 on 2021-09-08 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='Table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.table'),
        ),
    ]
