# Generated by Django 3.2.7 on 2021-09-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Fo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
