# Generated by Django 3.2.7 on 2021-09-12 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_category_fo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Fo',
        ),
        migrations.AddField(
            model_name='table',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feed.platform'),
            preserve_default=False,
        ),
    ]
