# Generated by Django 3.2.7 on 2021-09-13 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20210912_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='fieldForDisplay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.cell'),
        ),
    ]
